=== goddtriffin/purdoobahs.com/assets/purdoobahs/_purdoobah.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.purdoobahs.com/schemas/_purdoobah.schema.json",
  "type": "object",
  "additionalProperties": false,
  "title": "Purdoobah",
  "description": "A Purdoobah",
  "required": ["name", "birth_certificate_name", "marching", "education", "hometown"],
  "properties": {
    "name": {
      "type": "string",
      "title": "Name",
      "description": "This Purdoobah's nickname"
    },
    "birth_certificate_name": {
      "type": "object",
      "additionalProperties": false,
      "title": "Birth Certificate Name",
      "description": "This Purdoobah's real name",
      "required": ["first", "last"],
      "properties": {
        "first": {
          "type": "string",
          "title": "First Name",
          "description": "This Purdoobah's first name"
        },
        "middle": {
          "type": "string",
          "title": "Middle Name",
          "description": "This Purdoobah's middle name"
        },
        "last": {
          "type": "string",
          "title": "Last Name",
          "description": "This Purdoobah's last name"
        }
      }
    },
    "emoji": {
      "type": "string",
      "title": "Emoji",
      "description": "An emoji related to this Purdoobah's nickname"
    },
    "marching": {
      "type": "object",
      "additionalProperties": false,
      "title": "Marching",
      "description": "All details about this Purdoobah's marching career",
      "required": ["years_marched"],
      "properties": {
        "years_marched": {
          "type": "array",
          "title": "Years Marched",
          "description": "A list of all the years this Purdoobah marched",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "shoutout": {
          "type": "string",
          "format": "iri-reference",
          "title": "Shoutout",
          "description": "A link to this Purdoobah's Instagram shoutout post"
        }
      }
    },
    "education": {
      "type": "object",
      "additionalProperties": false,
      "title": "Education",
      "description": "All details about this Purdoobah's educational career at Purdue",
      "required": ["major", "year"],
      "properties": {
        "major": {
          "type": "string",
          "title": "Major",
          "description": "This Purdoobah's educational Major"
        },
        "minor": {
          "type": "string",
          "title": "Minor",
          "description": "This Purdoobah's educational Minor"
        },
        "year": {
          "type": "string",
          "title": "Year",
          "description": "This Purdoobah's year in school",
          "enum": ["freshman", "sophomore", "junior", "senior", "super-senior", "alumni"]
        }
      }
    },
    "hometown": {
      "type": "object",
      "additionalProperties": false,
      "title": "Home",
      "description": "The hometown of this Purdoobah",
      "required": ["city", "state"],
      "properties": {
        "city": {
          "type": "string",
          "title": "City",
          "description": "The city where this Purdoobah grew up"
        },
        "state": {
          "type": "string",
          "title": "State",
          "description": "The state where this Purdoobah grew up"
        }
      }
    },
    "alumni": {
      "type": "object",
      "additionalProperties": false,
      "title": "Alumni",
      "description": "All details about this Purdoobah's post-grad life",
      "required": [],
      "properties": {
        "job": {
          "type": "string",
          "title": "Job",
          "description": "This Purdoobah's real life job"
        }
      }
    },
    "personal": {
      "type": "object",
      "additionalProperties": false,
      "title": "Personality",
      "description": "Fun facts about this Purdoobah",
      "required": [],
      "properties": {
        "hobbies": {
          "type": "array",
          "title": "Hobbies",
          "description": "A list of this Purdoobah's hobbies",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "socials": {
          "type": "object",
          "additionalProperties": false,
          "title": "Socials",
          "description": "Links to this Purdoobah's social media accounts",
          "required": [],
          "properties": {
            "facebook": {
              "type": "string",
              "format": "iri-reference",
              "title": "Facebook",
              "description": "A link to this Purdoobah's Facebook account"
            },
            "instagram": {
              "type": "string",
              "format": "iri-reference",
              "title": "Instagram",
              "description": "A link to this Purdoobah's Instagram account"
            },
            "linkedin": {
              "type": "string",
              "format": "iri-reference",
              "title": "LinkedIn",
              "description": "A link to this Purdoobah's LinkedIn account"
            }
          }
        }
      }
    },
    "achievements": {
      "type": "object",
      "additionalProperties": false,
      "title": "Achievements",
      "description": "The achievements this Purdoobah garnered during their tenure",
      "required": [],
      "properties": {
        "student_leader": {
          "type": "array",
          "title": "Student Leader",
          "description": "The years this Purdoobah has been a section leader",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "bottom_feeder_committee": {
          "type": "boolean",
          "title": "Bottom Feeder Committee",
          "description": "If this Purdoobah was a member of the Bottom Feeder Committee"
        },
        "spoonsassins_victories": {
          "type": "array",
          "title": "Spoon-sassins Winner",
          "description": "The years this Purdoobah was a winner of Spoon-sassins",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "kappa_kappa_psi": {
          "type": "boolean",
          "title": "Kappa Kappa Psi",
          "description": "If this Purdoobah was an honorary member of the Kappa Kappa Psi band service fraternity"
        },
        "tau_beta_sigma": {
          "type": "boolean",
          "title": "Tau Beta Sigma",
          "description": "If this Purdoobah was an honorary member of the Tau Beta Sigma band service sorority"
        }
      }
    }
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/amanda-brinkofski.json
{
  "name": "Amanda Brinkofski",
  "birth_certificate_name": {
    "first": "Amanda",
    "last": "Brinkofski"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2002]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/domino.json
{
  "name": "Domino",
  "birth_certificate_name": {
    "first": "William",
    "last": "Rater"
  },
  "emoji": "ðŸŽ²",
  "marching": {
    "years_marched": [2020]
  },
  "education": {
    "major": "Political Science",
    "minor": "Environmental Science",
    "year": "freshman"
  },
  "hometown": {
    "city": "Valparaiso",
    "state": "Indiana"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/holdoor.json
{
  "name": "Holdoor",
  "birth_certificate_name": {
    "first": "Logan",
    "last": "Juran"
  },
  "emoji": "ðŸšª",
  "marching": {
    "years_marched": [2019, 2020],
    "shoutout": "https://www.instagram.com/p/CFH7rLWlllR/"
  },
  "education": {
    "major": "Pharmacy",
    "year": "sophomore"
  },
  "hometown": {
    "city": "Highland",
    "state": "Indiana"
  },
  "personal": {
    "hobbies": [
      "playing guitar",
      "swimming",
      "hanging out with his friends"
    ]
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/mfs.json
{
  "name": "MFS",
  "birth_certificate_name": {
    "first": "Mike",
    "last": "Sheehan"
  },
  "emoji": "",
  "marching": {
    "years_marched": [-1]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/flounder.json
{
  "name": "Flounder",
  "birth_certificate_name": {
    "first": "Sean",
    "last": "Knickerbocker"
  },
  "emoji": "üêü",
  "marching": {
    "years_marched": [2018, 2019, 2020],
    "shoutout": "https://www.instagram.com/p/CFceFkUF2nF/"
  },
  "education": {
    "major": "Insect Biology w/ concentration in Forensic Entomology",
    "minor": "Criminal Justice and Forensics",
    "year": "junior"
  },
  "hometown": {
    "city": "Peru",
    "state": "Indiana"
  },
  "personal": {
    "hobbies": [
      "hanging out with friends"
    ]
  },
  "achievements": {
    "bottom_feeder_committee": true
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/mr-moeschberger.json
{
  "name": "Mr. Moeschberger",
  "birth_certificate_name": {
    "first": "Mr.",
    "last": "Moeschberger"
  },
  "emoji": "üèÅ",
  "marching": {
    "years_marched": [1998, 1999, 2000, 2001, 2002],
    "shoutout": "https://www.instagram.com/p/CMutZ6ZFWb9/"
  },
  "education": {
    "major": "Social Studies Education",
    "year": "alumni"
  },
  "hometown": {
    "city": "Kokomo",
    "state": "Indiana"
  },
  "alumni": {
    "job": "Camp director and Chief Fun Officer"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/orville-redenbacher.json
{
  "name": "Orville Redenbacher",
  "birth_certificate_name": {
    "first": "Orville",
    "middle": "Clarence",
    "last": "Redenbacher"
  },
  "emoji": "üçø",
  "marching": {
    "years_marched": [1925, 1926, 1927, 1928],
    "shoutout": ""
  },
  "education": {
    "major": "Agronomy",
    "minor": "",
    "year": "alumni"
  },
  "hometown": {
    "city": "Brazil",
    "state": "Indiana"
  },
  "alumni": {
    "job": "Founder of Orville Redenbacher's Gourmet Popping Corn"
  },
  "personal": {
    "hobbies": [],
    "socials": {
      "facebook": "https://www.facebook.com/orvilleredenbachers/",
      "instagram": "https://www.instagram.com/orvillepopcorn/"
    }
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/rolex.json
{
  "name": "Rolex",
  "birth_certificate_name": {
    "first": "Aaron",
    "last": "Cruz"
  },
  "emoji": "‚è±",
  "marching": {
    "years_marched": [2017, 2018, 2020],
    "shoutout": "https://www.instagram.com/p/CHx9_V4lS9N/"
  },
  "education": {
    "major": "Acting/Theatre",
    "year": "senior"
  },
  "hometown": {
    "city": "Elwood",
    "state": "Indiana"
  }
}
