=== goddtriffin/purdoobahs.com/assets/purdoobahs/_purdoobah.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://www.purdoobahs.com/schemas/_purdoobah.schema.json",
  "type": "object",
  "additionalProperties": false,
  "title": "Purdoobah",
  "description": "A Purdoobah",
  "required": ["name", "birth_certificate_name", "marching", "education", "hometown"],
  "properties": {
    "name": {
      "type": "string",
      "title": "Name",
      "description": "This Purdoobah's nickname"
    },
    "birth_certificate_name": {
      "type": "object",
      "additionalProperties": false,
      "title": "Birth Certificate Name",
      "description": "This Purdoobah's real name",
      "required": ["first", "last"],
      "properties": {
        "first": {
          "type": "string",
          "title": "First Name",
          "description": "This Purdoobah's first name"
        },
        "middle": {
          "type": "string",
          "title": "Middle Name",
          "description": "This Purdoobah's middle name"
        },
        "last": {
          "type": "string",
          "title": "Last Name",
          "description": "This Purdoobah's last name"
        }
      }
    },
    "emoji": {
      "type": "string",
      "title": "Emoji",
      "description": "An emoji related to this Purdoobah's nickname"
    },
    "marching": {
      "type": "object",
      "additionalProperties": false,
      "title": "Marching",
      "description": "All details about this Purdoobah's marching career",
      "required": ["years_marched"],
      "properties": {
        "years_marched": {
          "type": "array",
          "title": "Years Marched",
          "description": "A list of all the years this Purdoobah marched",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "shoutout": {
          "type": "string",
          "format": "iri-reference",
          "title": "Shoutout",
          "description": "A link to this Purdoobah's Instagram shoutout post"
        }
      }
    },
    "education": {
      "type": "object",
      "additionalProperties": false,
      "title": "Education",
      "description": "All details about this Purdoobah's educational career at Purdue",
      "required": ["major", "year"],
      "properties": {
        "major": {
          "type": "string",
          "title": "Major",
          "description": "This Purdoobah's educational Major"
        },
        "minor": {
          "type": "string",
          "title": "Minor",
          "description": "This Purdoobah's educational Minor"
        },
        "year": {
          "type": "string",
          "title": "Year",
          "description": "This Purdoobah's year in school",
          "enum": ["freshman", "sophomore", "junior", "senior", "super-senior", "alumni"]
        }
      }
    },
    "hometown": {
      "type": "object",
      "additionalProperties": false,
      "title": "Home",
      "description": "The hometown of this Purdoobah",
      "required": ["city", "state"],
      "properties": {
        "city": {
          "type": "string",
          "title": "City",
          "description": "The city where this Purdoobah grew up"
        },
        "state": {
          "type": "string",
          "title": "State",
          "description": "The state where this Purdoobah grew up"
        }
      }
    },
    "alumni": {
      "type": "object",
      "additionalProperties": false,
      "title": "Alumni",
      "description": "All details about this Purdoobah's post-grad life",
      "required": [],
      "properties": {
        "job": {
          "type": "string",
          "title": "Job",
          "description": "This Purdoobah's real life job"
        }
      }
    },
    "personal": {
      "type": "object",
      "additionalProperties": false,
      "title": "Personality",
      "description": "Fun facts about this Purdoobah",
      "required": [],
      "properties": {
        "hobbies": {
          "type": "array",
          "title": "Hobbies",
          "description": "A list of this Purdoobah's hobbies",
          "items": {
            "type": "string"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "socials": {
          "type": "object",
          "additionalProperties": false,
          "title": "Socials",
          "description": "Links to this Purdoobah's social media accounts",
          "required": [],
          "properties": {
            "facebook": {
              "type": "string",
              "format": "iri-reference",
              "title": "Facebook",
              "description": "A link to this Purdoobah's Facebook account"
            },
            "instagram": {
              "type": "string",
              "format": "iri-reference",
              "title": "Instagram",
              "description": "A link to this Purdoobah's Instagram account"
            },
            "linkedin": {
              "type": "string",
              "format": "iri-reference",
              "title": "LinkedIn",
              "description": "A link to this Purdoobah's LinkedIn account"
            }
          }
        }
      }
    },
    "achievements": {
      "type": "object",
      "additionalProperties": false,
      "title": "Achievements",
      "description": "The achievements this Purdoobah garnered during their tenure",
      "required": [],
      "properties": {
        "student_leader": {
          "type": "array",
          "title": "Student Leader",
          "description": "The years this Purdoobah has been a section leader",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "bottom_feeder_committee": {
          "type": "boolean",
          "title": "Bottom Feeder Committee",
          "description": "If this Purdoobah was a member of the Bottom Feeder Committee"
        },
        "spoonsassins_victories": {
          "type": "array",
          "title": "Spoon-sassins Winner",
          "description": "The years this Purdoobah was a winner of Spoon-sassins",
          "items": {
            "type": "integer"
          },
          "minItems": 1,
          "uniqueItems": true
        },
        "kappa_kappa_psi": {
          "type": "boolean",
          "title": "Kappa Kappa Psi",
          "description": "If this Purdoobah was an honorary member of the Kappa Kappa Psi band service fraternity"
        },
        "tau_beta_sigma": {
          "type": "boolean",
          "title": "Tau Beta Sigma",
          "description": "If this Purdoobah was an honorary member of the Tau Beta Sigma band service sorority"
        }
      }
    }
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/mat-king.json
{
  "name": "Mat King",
  "birth_certificate_name": {
    "first": "Mat",
    "last": "King"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2002]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/ryan-howard.json
{
  "name": "Ryan Howard",
  "birth_certificate_name": {
    "first": "Ryan",
    "last": "Howard"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2002]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/velveeta.json
{
  "name": "Velveeta",
  "birth_certificate_name": {
    "first": "Reagan",
    "last": "Duffy"
  },
  "emoji": "ðŸ¤¢",
  "marching": {
    "years_marched": [2020],
    "shoutout": "https://www.instagram.com/p/CFuUEovFhD2/"
  },
  "education": {
    "major": "Actuarial Science / Statistics",
    "minor": "Economics / MGMT / Environmental Policy",
    "year": "junior"
  },
  "hometown": {
    "city": "Vero Beach",
    "state": "Florida"
  },
  "personal": {
    "hobbies": [
      "watching stand-up comedy",
      "painting"
    ]
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/reno.json
{
  "name": "Reno",
  "birth_certificate_name": {
    "first": "Matthew",
    "last": "Radford"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2017, 2018]
  },
  "education": {
    "major": "",
    "minor": "",
    "year": "senior"
  },
  "hometown": {
    "city": "Nashville",
    "state": "Tennessee"
  },
  "achievements": {
    "bottom_feeder_committee": true
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/nick-soboleski.json
{
  "name": "Nick Soboleski",
  "birth_certificate_name": {
    "first": "Nick",
    "last": "Soboleski"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2002]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/jenny-campbell.json
{
  "name": "Jenny Campbell",
  "birth_certificate_name": {
    "first": "Jenny",
    "last": "Campbell"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2000]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/dart.json
{
  "name": "Dart",
  "birth_certificate_name": {
    "first": "Taylor",
    "last": "Kern"
  },
  "emoji": "",
  "marching": {
    "years_marched": [2016]
  },
  "education": {
    "major": "unknown",
    "year": "alumni"
  },
  "hometown": {
    "city": "unknown",
    "state": "unknown"
  }
}

=== goddtriffin/purdoobahs.com/assets/purdoobahs/turkey.json
{
  "name": "Turkey",
  "birth_certificate_name": {
    "first": "Matthew",
    "last": "Gobel"
  },
  "emoji": "ðŸ¦ƒ",
  "marching": {
    "years_marched": [2018, 2019, 2020]
  },
  "education": {
    "major": "Agricultural Engineering",
    "year": "junior"
  },
  "hometown": {
    "city": "Oxford",
    "state": "Indiana"
  },
  "achievements": {
    "student_leader": [2019, 2020]
  }
}
